---
title: "p8105_hw1_xz3499.Rmd"
author: "Xintong Zhao"
date: '`r Sys.Date()`'
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problem 1

### 1. Load required libraries
```{r, message=FALSE}
library(moderndive)
library(ggplot2)
library(dplyr)
```

### 2. Load the dataset
```{r}
data("early_january_weather")
```

### 3. View basic dataset information
```{r}
# quickly view the data
summary(early_january_weather)
```
### 4. A short discription of the dataset
```{r, results='asis'}
# the variables in this dataset 
variables <- names(early_january_weather)
cat("The dataset contains the following variables:", paste(variables, collapse = ", "), ".\n")

# the size of the dataset
n_rows <- nrow(early_january_weather)
n_cols <- ncol(early_january_weather)
cat("The dataset has", n_rows, "rows and", n_cols, "columns.\n")

# the mean temperature
mean_temp_value <- mean(early_january_weather$temp, na.rm = TRUE)
cat("The mean temperature is", round(mean_temp_value, 1), "°F.")
```

### 5. Create scatterplot
```{r}
scatter_plot <- ggplot(early_january_weather, aes(x = time_hour, y = temp, color = humid)) +
  geom_point() +
  labs(x = "Time", y = "Temperature (°F)", color = "Humidity") +
  theme_minimal()

# display the plot
print(scatter_plot)

# save the plot
ggsave("temp_vs_time.png", plot = scatter_plot, width = 8, height = 6)
```

